"""bcg.construct.light — streaming belief-content graph.

Belief-graph construction backend that uses local embeddings + a small
generative model instead of one large API-based chat model: semantic chunks
are extracted concurrently by a small Qwen model, stance is inferred by a
local DeBERTa zero-shot classifier, entities by local spaCy NER, and typed
relations by a separate non-thinking Qwen model. See the sibling
``construct.api_based`` package for the alternative large-API-model backend.

Nodes are generated from semantic chunks, belief nodes may be merged by
embeddings, and typed relations are generated by a non-thinking Qwen model.
The batch and HTTP entry points share the same
``StreamingBeliefBuilder`` implementation and ``StreamOptions`` configuration.
"""

__version__ = "3.1.0"

from .graph import BeliefGraph
from .stream import StreamingBeliefBuilder, StreamOptions

__all__ = ["BeliefGraph", "StreamingBeliefBuilder", "StreamOptions", "__version__"]
