"""
graph.py
========
The in-memory belief graph mutated by the streaming engine.

Current schema:
  * nodes / beliefs — dict id -> active node. A node has node_type="belief" or
                      node_type="decision". The public attribute remains named
                      ``beliefs`` for compatibility with merge code.
  * evidence        — dict id -> evidence node. Belief/decision nodes hold
                      evidence_ids instead of embedded evidence records.
  * relations       — typed edges between nodes generated by the edge model.
  * merges          — audit records of applied node merges.
  * sessions        — per-run summaries appended at trajectory end.

Ids are allocated monotonically as nodes are created, but relations are not
constrained by chronological direction.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .confidence import normalize_confidence_config


DEFAULT_RELATION_TYPES = {"depends_on", "supplements", "contradicts"}


class BeliefGraph:
    def __init__(
        self,
        confidence_config: Optional[Dict[str, Any]] = None,
        valid_relation_types: Optional[set[str]] = None,
    ) -> None:
        self.beliefs: Dict[int, Dict[str, Any]] = {}
        self.evidence: Dict[int, Dict[str, Any]] = {}
        self.relations: List[Dict[str, Any]] = []
        self.merges: List[Dict[str, Any]] = []
        self.sessions: List[Dict[str, Any]] = []
        self._next_id = 0
        self._next_evidence_id = 0
        self._next_relation_id = 0
        self.confidence_config = normalize_confidence_config(confidence_config)
        self.valid_relation_types = set(
            DEFAULT_RELATION_TYPES if valid_relation_types is None else valid_relation_types
        )

    @property
    def next_id(self) -> int:
        return self._next_id

    def allocate_id(self) -> int:
        value = self._next_id
        self._next_id += 1
        return value

    def add_belief(self, belief: Dict[str, Any]) -> None:
        belief_id = belief.get("id")
        if not isinstance(belief_id, int):
            raise ValueError("node must carry an int 'id' (use allocate_id())")
        belief.setdefault("node_type", "belief")
        belief.setdefault("evidence_ids", [])
        belief.pop("evidence", None)
        self.beliefs[belief_id] = belief

    def remove_belief(self, belief_id: int) -> Optional[Dict[str, Any]]:
        return self.beliefs.pop(belief_id, None)

    def allocate_evidence_id(self) -> int:
        value = self._next_evidence_id
        self._next_evidence_id += 1
        return value

    def add_evidence(self, evidence: Dict[str, Any]) -> int:
        evidence_id = evidence.get("id")
        if not isinstance(evidence_id, int):
            evidence_id = self.allocate_evidence_id()
        rest = dict(evidence)
        rest.pop("id", None)
        record = {"id": evidence_id}
        record.update(rest)
        record.setdefault("node_type", "evidence")
        self.evidence[evidence_id] = record
        if evidence_id >= self._next_evidence_id:
            self._next_evidence_id = evidence_id + 1
        return evidence_id

    def get_evidence(self, evidence_id: int) -> Optional[Dict[str, Any]]:
        return self.evidence.get(evidence_id)

    def evidence_records(self, evidence_ids: List[int]) -> List[Dict[str, Any]]:
        records: List[Dict[str, Any]] = []
        for raw_id in evidence_ids or []:
            try:
                evidence_id = int(raw_id)
            except (TypeError, ValueError):
                continue
            record = self.evidence.get(evidence_id)
            if record is not None:
                records.append(record)
        return records

    def prune_unreferenced_evidence(self) -> Dict[str, Any]:
        """Remove evidence records no active node references.

        Merge-time evidence deduplication keeps the first evidence id for each
        semantic evidence key. Duplicate ids and evidence owned only by absorbed
        nodes therefore become unreferenced and are removed here.
        """
        referenced: set[int] = set()
        for node in self.beliefs.values():
            for raw_id in node.get("evidence_ids") or []:
                try:
                    referenced.add(int(raw_id))
                except (TypeError, ValueError):
                    continue
        removed_ids = sorted(set(self.evidence) - referenced)
        for evidence_id in removed_ids:
            self.evidence.pop(evidence_id, None)
        return {
            "removed_ids": removed_ids,
            "n_removed": len(removed_ids),
            "n_remaining": len(self.evidence),
        }

    def active(self) -> List[Dict[str, Any]]:
        return [self.beliefs[node_id] for node_id in sorted(self.beliefs)]

    def ids(self) -> List[int]:
        return sorted(self.beliefs)

    def allocate_relation_id(self) -> int:
        value = self._next_relation_id
        self._next_relation_id += 1
        return value

    @staticmethod
    def _rel_key(relation: Dict[str, Any]) -> Tuple[int, int, str]:
        return (
            relation.get("from_id"),
            relation.get("to_id"),
            relation.get("type"),
        )

    def add_relations(self, relations: List[Dict[str, Any]]) -> int:
        seen = {self._rel_key(relation) for relation in self.relations}
        active_ids = set(self.beliefs)
        added = 0
        for relation in relations:
            try:
                from_id = int(relation.get("from_id"))
                to_id = int(relation.get("to_id"))
            except (TypeError, ValueError):
                continue
            relation_type = relation.get("type")
            if relation_type not in self.valid_relation_types:
                continue
            if from_id == to_id or from_id not in active_ids or to_id not in active_ids:
                continue
            note = relation.get("note", "") or ""
            if not isinstance(note, str):
                note = str(note)
            relation_id = relation.get("id")
            if not isinstance(relation_id, int):
                relation_id = self.allocate_relation_id()
            clean = {
                "id": relation_id,
                "from_id": from_id,
                "to_id": to_id,
                "type": relation_type,
                "note": note.strip(),
            }
            key = self._rel_key(clean)
            if key in seen:
                continue
            seen.add(key)
            self.relations.append(clean)
            if relation_id >= self._next_relation_id:
                self._next_relation_id = relation_id + 1
            added += 1
        return added

    def remap_relations(self, mapping: Dict[int, int]) -> Dict[str, Any]:
        """Rewrite relation endpoints after a merge and drop loops/duplicates."""
        report = {"rewritten": 0, "dropped_self": 0, "dropped_duplicate": 0}
        out: List[Dict[str, Any]] = []
        seen: set = set()
        for relation in self.relations:
            from_id = mapping.get(relation["from_id"], relation["from_id"])
            to_id = mapping.get(relation["to_id"], relation["to_id"])
            changed = from_id != relation["from_id"] or to_id != relation["to_id"]
            if from_id == to_id:
                report["dropped_self"] += 1
                continue
            key = (from_id, to_id, relation.get("type"))
            if key in seen:
                report["dropped_duplicate"] += 1
                continue
            seen.add(key)
            if changed:
                relation = dict(relation)
                relation["from_id"], relation["to_id"] = from_id, to_id
                report["rewritten"] += 1
            out.append(relation)
        self.relations = out
        return report

    def snapshot(self, extra: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        nodes = self.active()
        snapshot: Dict[str, Any] = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "n_nodes": len(self.beliefs),
            "n_beliefs": sum(
                1 for node in nodes if node.get("node_type", "belief") == "belief"
            ),
            "n_decisions": sum(
                1 for node in nodes if node.get("node_type") == "decision"
            ),
            "nodes": nodes,
            "beliefs": [
                node for node in nodes if node.get("node_type", "belief") == "belief"
            ],
            "decisions": [node for node in nodes if node.get("node_type") == "decision"],
            "evidence": [self.evidence[i] for i in sorted(self.evidence)],
            "relations": list(self.relations),
            "merges": list(self.merges),
            "sessions": list(self.sessions),
        }
        if extra:
            snapshot.update(extra)
        return snapshot

    def save_snapshot(self, path: Any, extra: Optional[Dict[str, Any]] = None) -> None:
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as handle:
            json.dump(self.snapshot(extra), handle, ensure_ascii=False, indent=2)
