// Generated by contracts/generate_ts_types.py from contracts/http.schema.json.
// DO NOT EDIT BY HAND. Run `uv run python contracts/generate_ts_types.py` to regenerate.
// Schema version: 1

export const BCG_SCHEMA_VERSION = 1;

export interface BcgTurn {
	problem_id: string;
	role: "assistant" | "system" | "tool" | "user";
	content: string;
	is_message_end?: boolean;
	is_trajectory_end?: boolean;
	date?: string;
	session_date?: string;
}

export interface BcgNode {
	id: number;
	node_type: "belief" | "decision";
	belief?: string;
	decision?: string;
	confidence?: number;
	stance?: string;
	role?: string;
	layer?: string;
	source?: Record<string, unknown>;
	evidence_ids?: number[];
	factor_ids?: number[];
	supporting_excerpts?: string[];
	merged_from?: number[];
	confidence_history?: unknown[];
}

export interface BcgRelation {
	id: number;
	from_id: number;
	to_id: number;
	type: "depends_on" | "supplements" | "contradicts";
	note?: string;
	weight?: number;
	activated_condition?: string;
}

export interface BcgSnapshot {
	problem_id?: string;
	item_id?: string;
	stage?: "turn" | "buffered" | "final" | "empty" | "query";
	finalized?: boolean;
	stream_turn_index?: number;
	n_turns_ingested?: number;
	generated_at: string;
	n_nodes: number;
	n_beliefs: number;
	n_decisions: number;
	nodes: BcgNode[];
	beliefs: BcgNode[];
	decisions: BcgNode[];
	evidence?: Record<string, unknown>;
	relations: BcgRelation[];
	merges?: unknown[];
	sessions?: unknown[];
}

export interface BcgErrorEnvelope {
	error: string;
}

export interface BcgHealth {
	status: "ok";
	active: string[];
	all: string[];
	schema_version: number;
}

export type BcgTurnsRequest = BcgTurn[];

export interface BcgTurnsResponse {
	pushed: number;
	finalized: string[];
	latest: Record<string, BcgSnapshot>;
}

export interface BcgFinalizeRequest {
	problem_id: string;
}

export interface BcgReleaseRequest {
	problem_id: string;
}

export interface BcgReleaseResponse {
	problem_id: string;
	released: boolean;
}
