"""bcg.construct.hybrid — streaming belief-content graph.

Belief-graph construction backend that uses local embeddings + a small
generative model instead of one unified graph LLM pipeline: semantic chunks
are extracted concurrently by a small Qwen model, stance is inferred by a
local DeBERTa zero-shot classifier, entities by local spaCy NER, and typed
relations by a separate non-thinking Qwen model. See the sibling
``construct.unified`` package for the alternative unified-model backend.

Nodes are generated from semantic chunks, belief nodes may be merged by
embeddings, and typed relations are generated by a non-thinking Qwen model.
The batch and HTTP entry points share the same
``StreamingBeliefBuilder`` implementation and ``StreamOptions`` configuration.

``__version__`` is the package version (pyproject metadata is the single
source); the historical "3.1.0" backend lineage is kept in this docstring.
"""

from bcg import _package_version as _bcg_version

__version__ = _bcg_version()

from .graph import BeliefGraph
from .stream import StreamingBeliefBuilder, StreamOptions

__all__ = ["BeliefGraph", "StreamingBeliefBuilder", "StreamOptions", "__version__"]
