#!/usr/bin/env python3
"""Generate TypeScript types from contracts/http.schema.json.

The generated file is the single TS view of the BCG HTTP contract; agent-cli
consumes it instead of hand-written type assertions. Run with --check to
verify the checked-in file is up to date (used by `make check-contracts`).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "contracts" / "http.schema.json"
OUTPUT = ROOT / "agent-cli" / "src" / "core" / "context" / "bcg-contract.types.ts"

TS_TYPES = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
}


def _type_name(ref: str) -> str:
    return "Bcg" + ref.rsplit("/", 1)[-1][0].upper() + ref.rsplit("/", 1)[-1][1:]


def _ref_name(ref: str) -> str:
    return _type_name(ref)


def _ts_type(schema: dict, defs: dict) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "enum" in schema:
        values = " | ".join(json.dumps(v) for v in schema["enum"])
        return values or "string"
    kind = schema.get("type")
    if kind == "array":
        items = schema.get("items", {})
        return f"{_ts_type(items, defs)}[]"
    if kind == "object":
        props = schema.get("properties")
        if not props and "additionalProperties" in schema:
            value = schema["additionalProperties"]
            if isinstance(value, dict):
                return f"Record<string, {_ts_type(value, defs)}>"
            return "Record<string, unknown>"
        return "Record<string, unknown>"
    if kind in TS_TYPES:
        return TS_TYPES[kind]
    return "unknown"


def _render_interface(name: str, schema: dict, defs: dict) -> list[str]:
    lines = [f"export interface {_type_name(name)} {{"]
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    for prop_name, prop_schema in props.items():
        optional = "" if prop_name in required else "?"
        lines.append(f"\t{prop_name}{optional}: {_ts_type(prop_schema, defs)};")
    additional = schema.get("additionalProperties")
    if isinstance(additional, dict) and "$ref" in additional:
        lines.append(f"\t[key: string]: {_ref_name(additional['$ref'])};")
    lines.append("}")
    return lines


def generate() -> str:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    defs = schema["$defs"]
    lines = [
        "// Generated by contracts/generate_ts_types.py from contracts/http.schema.json.",
        "// DO NOT EDIT BY HAND. Run `uv run python contracts/generate_ts_types.py` to regenerate.",
        "// Schema version: " + str(schema.get("schema_version", 1)),
        "",
        "export const BCG_SCHEMA_VERSION = "
        + str(schema.get("schema_version", 1))
        + ";",
        "",
    ]
    for name in ("turn", "node", "relation", "snapshot", "errorEnvelope", "health"):
        if name in defs:
            lines.extend(_render_interface(name, defs[name], defs))
            lines.append("")
    for name in (
        "turnsRequest",
        "turnsResponse",
        "finalizeRequest",
        "releaseRequest",
        "releaseResponse",
        "contextSelectionRequest",
        "contextSelectionResponse",
    ):
        if name in defs:
            d = defs[name]
            if d.get("type") == "array":
                lines.append(f"export type {_type_name(name)} = {_ts_type(d, defs)};")
            else:
                lines.extend(_render_interface(name, d, defs))
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()
    rendered = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"ERROR: {OUTPUT} is stale; run contracts/generate_ts_types.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT} matches contracts/http.schema.json")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
